[project]
name = "stock-market-insights"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "yfinance==1.0",
    "pandas>=2.0.0",
    "numpy>=1.24.0"
    ]
